services:
  psql:
    image: postgres:14
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - internal

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: local
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - psql
    ports:
      - "8000:8000"
    networks:
      - internal
    stdin_open: true
    tty: true
    command: sh -c "pip install -q -r /app/requirements.txt && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7-alpine
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgresql:
    name: mtg_postgresql
    external: true
  pgadmin-data: {}
