# Generated by Django 4.2.16 on 2026-09-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binders', '0010_move_card_to_cards'),
        ('carts', '0007_cart_source_cartitem_price_ars'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('foil', models.BooleanField(default=False)),
                ('etched', models.BooleanField(default=False)),
                ('binder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='binders.binder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='carts.cartitem')),
            ],
        ),
    ]
