# Generated by Django 4.2.16 on 2024-11-11 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Binder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("set_name", models.CharField(max_length=255)),
                ("color_identity", models.CharField(max_length=255)),
                ("uri", models.CharField(max_length=32)),
                ("scryfall_uri", models.CharField(max_length=255)),
                ("image_uri", models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BinderCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "binder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="binders.binder"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="binders.card"
                    ),
                ),
            ],
            options={
                "unique_together": {("binder", "card")},
            },
        ),
    ]
