# Generated by Django 4.2.16 on 2024-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("binders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="binders",
            field=models.ManyToManyField(
                blank=True, through="binders.BinderCard", to="binders.binder"
            ),
        ),
    ]
