# Generated by Django 4.2.16 on 2025-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binders', '0002_card_binders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindercard',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='uri',
            field=models.CharField(max_length=255),
        ),
    ]
