# Generated by Django 4.2.16 on 2025-05-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binders', '0003_alter_bindercard_quantity_alter_card_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindercard',
            name='etched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bindercard',
            name='foil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='price_usd_etched',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='price_usd_foil',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
