# Generated by Django 4.2.16 on 2026-06-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binders', '0005_binder_is_public_card_set_code_card_type_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindercard',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
