# Generated by Django 4.2.16 on 2026-06-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binders', '0006_alter_bindercard_quantity_alter_card_name'),
        ('binders', '0006_wishlistcard'),
    ]

    operations = [
    ]
