# Generated by Django 4.2.16 on 2026-06-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binders', '0008_card_phash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistcard',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
