# Generated by Django 4.2.16 on 2026-09-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binders', '0010_move_card_to_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindercard',
            name='condition',
            field=models.CharField(choices=[('NM', 'Near Mint'), ('SP', 'Slightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='NM', max_length=3),
        ),
        migrations.AddField(
            model_name='bindercard',
            name='language',
            field=models.CharField(choices=[('EN', 'Inglés'), ('ES', 'Español'), ('PT', 'Portugués'), ('FR', 'Francés'), ('DE', 'Alemán'), ('IT', 'Italiano'), ('JA', 'Japonés'), ('KO', 'Coreano'), ('RU', 'Ruso'), ('ZHS', 'Chino simplificado'), ('ZHT', 'Chino tradicional')], default='EN', max_length=3),
        ),
    ]
