# Generated by Django 4.2.16 on 2026-09-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_collector_number'),
        ('binders', '0011_bindercard_condition_bindercard_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bindercard',
            unique_together={('binder', 'card', 'condition', 'language')},
        ),
    ]
