# Generated by Django 4.2.16 on 2026-09-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collector_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
