version: "3.8"
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app   # Mount the local project into the container
      - /app/node_modules  # Prevent overwriting node_modules in the container
    ports:
      - "3000:3000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
